services:
  api:
    image: ${COOKBOOK_IMAGE}
    volumes:
      - ~/config/.env:/app/config/.env
    ports:
      - '${API_PORT:-8000}:8000'

  redis:
    image: redis:7-alpine
    expose:
      - "6379"

  celery-beat:
    image: ${COOKBOOK_IMAGE}
    command: celery -A app.celery_app beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - config/.env

  celery-worker:
    image: ${COOKBOOK_IMAGE}
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - config/.env
