"""Added fridge

Revision ID: 0f51d81aed0c
Revises: fa70c605f619
Create Date: 2026-02-28 04:22:11.610842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f51d81aed0c'
down_revision: Union[str, Sequence[str], None] = 'fa70c605f619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'cholesterol')
    op.add_column('product', sa.Column('ingredient_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('product_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'ingredient', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The upgrade creates this FK unnamed, so Postgres assigns the default name.
    op.drop_constraint('product_ingredient_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_id_fkey'), 'product', 'ingredient', ['id'], ['id'])
    op.drop_column('product', 'ingredient_id')
    op.add_column('ingredient', sa.Column('cholesterol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
